export default[
  {
    'barcode_number': '017391128442',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 017391128442, EAN 0017391128442',
    'mpn': '729004ut',
    'model': '729004ut',
    'asin': 'B00GO4RC2K',
    'product_name': 'Red Lion Emoticon Knee High Sock ( Royal Blue - Medium )',
    'title': '',
    'category': 'Sporting Goods',
    'manufacturer': 'Standard Merchandising',
    'brand': 'Red Lion Socks',
    'label': 'Standard Merchandising',
    'author': '',
    'publisher': 'Standard Merchandising',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Royal',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '',
    'width': '',
    'height': '',
    'weight': '',
    'release_date': '',
    'description': 'Red Lion Emoticon Knee High Sock Medium Royal Blue ** The Happy Emoticon Is A Symbol Of Our Time. Enjoy These Acrylic Socks And Have Fun. Medium ( Sock Size Medium, Ladies Shoe Size 5-10, Mens Shoe Size 4.5-8.5 )',
    'features': [
      'These Socks Smile To the World',
      'Turned Welt Top',
      'Heel and Toe Construction',
      'Flat Knit Construction',
      'Made in the USA'
    ],
    'images': [],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '017391077900',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 017391077900, EAN 0017391077900',
    'mpn': '762604ut',
    'model': '762604ut',
    'asin': 'B0080QQ0KK',
    'product_name': 'Red Lion Baseball / Softball Socks ( Royal Blue - Small )',
    'title': '',
    'category': 'Sporting Goods',
    'manufacturer': 'Standard Merchandising',
    'brand': 'Red Lion Socks',
    'label': 'Standard Merchandising',
    'author': '',
    'publisher': 'Standard Merchandising',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Royal',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '5',
    'width': '4',
    'height': '1',
    'weight': '',
    'release_date': '',
    'description': 'Red Lion Baseball / Softball Socks Small Royal Blue ** Baseball, Softball, Fastpitch, Slowpitch Or T-Ball; These Are The Socks. The Ball Is Knit Into The Socks From Toe To Top. Small ( Sock Size Small, Youth Shoe Size Of 12-4, Ladies Shoe Size Of 4-5 ) , Medium ( Sock Size Medium, Ladies Shoe Size 5-10, Mens Shoe Size 4.5-8.5 ) , Large ( Sock Size Large, Ladies Shoe Size 11-12, Mens Shoe Size 9-12.5 )',
    'features': [
      'Baseball, Softball, Fast Pitch, Slow Pitch Even T-ball',
      'Ultra Soft Acrylic Body',
      'Ribbed Leg and Cushioned Foot',
      'Heel and Toe Construction for Better Fit',
      'Made in the USA'
    ],
    'images': [
      'https://images.barcodelookup.com/4585/45857473-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '017391042854',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 017391042854, EAN 0017391042854',
    'mpn': '7568f7ut',
    'model': '',
    'asin': 'B007VCVNXI',
    'product_name': 'Red Lion Florescent Patriot Athletic Sock ( Neon Pink - Large )',
    'title': '',
    'category': 'Sporting Goods',
    'manufacturer': 'Standard Merchandising',
    'brand': 'Red Lion Socks',
    'label': 'Standard Merchandising',
    'author': '',
    'publisher': 'Standard Merchandising',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': 'Large',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Neon Pink',
    'format': '',
    'package_quantity': '',
    'size': 'Large',
    'length': '4',
    'width': '3',
    'height': '0.25',
    'weight': '13',
    'release_date': '',
    'description': 'Red Lion Florescent Patriot Athletic Sock Large Neon Pink ** These Bright And Colorful Neon Athletic Tube Socks Can Be Worn While Playing Many Sports ( Volleyball, Soccer, Softball, Basketball, Cheer, Dance, Etc ) So Make Sure To Buy Enough For The Whole Team These Red Lion Athletic Socks Work Well For Multiple Sports Small ( Youth Shoe Size Of 12-4, Ladies Shoe Size Of 4-5 ) , Medium ( Sock Size Medium, Ladies Shoe Size 5-10, Mens Shoe Size 4 5-8 5 ) , Large ( Sock Size Large, Ladies Shoe Size 11-12, Mens Shoe Size 9-12 5 )',
    'features': [
      'Knee Hi',
      'Hot, Vibrant, Florescent Colors',
      'Made In The USA'
    ],
    'images': [
      'https://images.barcodelookup.com/5102/51021195-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '017391069646',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 017391069646, EAN 0017391069646',
    'mpn': '7998aeut',
    'model': '',
    'asin': 'B0079IXO72',
    'product_name': 'Red Lion Pink Ribbon Breast Cancer Socks Knee High ( Black / Pale Pink - Large )',
    'title': '',
    'category': 'Home & Garden > Household Supplies > Storage & Organization > Clothing & Closet Storage > Shoe Racks & Organizers',
    'manufacturer': 'Standard Merchandising',
    'brand': 'Red Lion Socks',
    'label': 'Standard Merchandising',
    'author': '',
    'publisher': 'Standard Merchandising',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': 'Large',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Black / Pale Pink',
    'format': '',
    'package_quantity': '',
    'size': 'Large',
    'length': '4',
    'width': '3',
    'height': '0.25',
    'weight': '13',
    'release_date': '',
    'description': 'Red Lion Pink Ribbon Breast Cancer Socks Knee High Large Black / Pale Pink ** Show Your Support With These Ribbon Socks. Many Different Causes Are Represented By The Various Colors, Pink, Gold, Purple, Blue And Green Are Offered. Great Way To Show Team Support For Your Cause. Small ( Sock Size Small, Youth Shoe Size Of 12-4, Ladies Shoe Size Of 4-5 ) Medium ( Sock Size Medium, Ladies Shoe Size 5-10, Mens Shoe Size 4.5-8.5 ) Large ( Sock Size Large, Ladies Shoe Size 11-12, Mens Shoe Size 9-12.5 )',
    'features': [
      'Breast Cancer Support Pink Ribbon',
      'Support Friend, Family and Neighbors',
      'Cushioned Acrylic Foot',
      'Heel and Toe Construction',
      'Made in the USA'
    ],
    'images': [
      'https://images.barcodelookup.com/5319/53199329-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '159572706X',
    'barcode_type': 'ISBN',
    'barcode_formats': 'ISBN 159572706X, ISBN 9781595727060',
    'mpn': '0978159572706',
    'model': '',
    'asin': '',
    'product_name': 'Red Socks',
    'title': '',
    'category': 'Media > Books',
    'manufacturer': '',
    'brand': '',
    'label': '',
    'author': '',
    'publisher': '',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': '',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '',
    'width': '',
    'height': '',
    'weight': '',
    'release_date': '',
    'description': 'Red Socks',
    'features': [],
    'images': [
      'https://images.barcodelookup.com/2980/29804548-1.jpg'
    ],
    'stores': [
      {
        'store_name': 'BetterWorld.com - New, Used, Rare Books & Textbooks',
        'store_price': '3.46',
        'product_url': 'https://www.betterworldbooks.com/red-socks-id-9781595727060.aspx',
        'currency_code': 'USD',
        'currency_symbol': '$'
      },
      {
        'store_name': 'Wal-Mart.com USA, LLC',
        'store_price': '6.99',
        'product_url': 'http://www.walmart.com/ip/Red-Socks/44451130',
        'currency_code': 'USD',
        'currency_symbol': '$'
      }
    ],
    'reviews': []
  },
  {
    'barcode_number': '017391080009',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 017391080009, EAN 0017391080009',
    'mpn': '8362zwut',
    'model': '',
    'asin': 'B00CQPCCH6',
    'product_name': 'Red Lion Gator All Sport Socks (Neon Green - Small)',
    'title': '',
    'category': 'Sporting Goods',
    'manufacturer': 'Standard Merchandising',
    'brand': 'Red Lion Socks',
    'label': 'Standard Merchandising',
    'author': '',
    'publisher': 'Standard Merchandising',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': 'Small',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Florescent Green',
    'format': '',
    'package_quantity': '',
    'size': 'Small',
    'length': '3',
    'width': '3',
    'height': '0.25',
    'weight': '19',
    'release_date': '',
    'description': "Fun Sport Socks with florescent green alligator print. Acrylic, Nylon, Polyester, & Spandex Blend / Cushioned Acrylic Foot / Heel & Toe Construction / Available in 2 sizes - Youth size 6-8.5 (fits shoe size 12-4) OR Adult Size Medium 9-11 (fits ladies shoe size 5-10 or men's shoe size 4.5 to 8.5) / Made in the USA / Knee High Length perfect for sport teams or everyday use.",
    'features': [
      'sport socks'
    ],
    'images': [
      'https://images.barcodelookup.com/5704/57047182-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '4897021353651',
    'barcode_type': 'EAN',
    'barcode_formats': 'EAN 4897021353651',
    'mpn': 'B05j1228',
    'model': 'Bg1030',
    'asin': 'B008AINK10',
    'product_name': 'Silly Socks Sneaker Socks, Red',
    'title': '',
    'category': 'Home & Garden > Household Supplies > Storage & Organization > Clothing & Closet Storage > Shoe Racks & Organizers',
    'manufacturer': 'Make My Day',
    'brand': 'Make My Day',
    'label': 'Make My Day',
    'author': '',
    'publisher': 'Make My Day',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': 'One Size',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': 'Red',
    'format': '',
    'package_quantity': '',
    'size': 'One Size',
    'length': '12',
    'width': '4',
    'height': '10',
    'weight': '',
    'release_date': '',
    'description': 'The SILLY SOCKS Sneaker Sock in red is a great gift for adults for any celebration and holiday. Includes two red socks that look like converse high tops. Non-slip sole; made of cotton. Socks go up to mid-calf. These super stretchy socks fit many shoe sizes for both women and men. Machine washable.',
    'features': [
      'Includes two red socks that look like converse high tops',
      'Non-slip sole',
      'Socks go up to mid-calf',
      'Fun, useful gift for adults',
      'Machine washable'
    ],
    'images': [
      'https://images.barcodelookup.com/4715/47157498-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '889938403912',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 889938403912, EAN 0889938403912',
    'mpn': 'X375',
    'model': '',
    'asin': '',
    'product_name': 'Holiday Sock Pack - Red',
    'title': '',
    'category': 'Apparel & Accessories > Clothing > Underwear & Socks > Socks',
    'manufacturer': 'The Tie Ba',
    'brand': '',
    'label': '',
    'author': '',
    'publisher': '',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': '',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '',
    'width': '',
    'height': '',
    'weight': '',
    'release_date': '',
    'description': 'Holiday Sock Pack - Red',
    'features': [],
    'images': [
      'https://images.barcodelookup.com/7155/71551571-1.jpg'
    ],
    'stores': [],
    'reviews': []
  },
  {
    'barcode_number': '1534725520',
    'barcode_type': 'ISBN',
    'barcode_formats': 'ISBN 1534725520, ISBN 9781534725522',
    'mpn': '',
    'model': '',
    'asin': '',
    'product_name': 'The Red Socks',
    'title': 'The Red Socks',
    'category': 'Media > Books',
    'manufacturer': '',
    'brand': '',
    'label': '',
    'author': 'Michael Vinsel',
    'publisher': 'CreateSpace Independent Publishing Platform',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': '',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '',
    'width': '',
    'height': '',
    'weight': '',
    'release_date': '',
    'description': 'The Red Socks',
    'features': [],
    'images': [
      'https://images.barcodelookup.com/6507/65072584-1.jpg'
    ],
    'stores': [
      {
        'store_name': 'ThriftBooks.com',
        'store_price': '15.74',
        'product_url': 'https://www.thriftbooks.com/w/the-red-socks_michael-david-vinsel/13895523/#isbn=1534725520',
        'currency_code': 'USD',
        'currency_symbol': '$'
      }
    ],
    'reviews': []
  },
  {
    'barcode_number': '078100003313',
    'barcode_type': 'UPC',
    'barcode_formats': 'UPC 078100003313, EAN 0078100003313',
    'mpn': '783311',
    'model': '',
    'asin': '',
    'product_name': 'Socks Clown Red Yellow',
    'title': '',
    'category': 'Electronics > Electronics Accessories > Power > Fuel Cells',
    'manufacturer': 'Morris Costumes',
    'brand': 'Morris Costumes',
    'label': '',
    'author': '',
    'publisher': '',
    'artist': '',
    'actor': '',
    'director': '',
    'studio': '',
    'genre': '',
    'audience_rating': '',
    'ingredients': '',
    'nutrition_facts': '',
    'color': '',
    'format': '',
    'package_quantity': '',
    'size': '',
    'length': '',
    'width': '',
    'height': '',
    'weight': '',
    'release_date': '',
    'description': 'Socks Clown Red Yellow',
    'features': [],
    'images': [
      'https://images.barcodelookup.com/9813/98130821-1.jpg'
    ],
    'stores': [
      {
        'store_name': 'Rakuten.com',
        'store_price': '22.05',
        'product_url': 'https://www.rakuten.com/shop/alliancesupply/product/BB401RY/?scid=af_feed',
        'currency_code': 'USD',
        'currency_symbol': '$'
      }
    ],
    'reviews': []
  }
];
